# .air.conf

# Air configuration
root = "."  # Root directory of the project
tmp_dir = "tmp"  # Temporary directory for build artifacts
exclude_dir = ["tmp","_trash","logs",".idea",".git", "vendor"]  # Directories to exclude from monitoring

# Environment variables for the project
[env]
  GO111MODULE = "on"  # Enable Go modules support

# Build and run configuration
[build]
  binary_name = "your_binary_name"  # Name of the binary to build
  exclude_dir = ["tmp","_trash","logs",".idea",".git", "vendor"]  # Directories to exclude from build
  exclude_file = ["*"]  # Files to exclude from build
  poll = true
  # Poll interval (defaults to the minimum interval of 500ms).
  poll_interval = 5000 # ms

  # Run configuration
  [build.run]
    cmd = "go run ."  # Command to run the project
    args = []  # Additional arguments for the command
    watcher = ["."]  # Directories to watch for changes
