FROM golang:latest AS builder


# Copy local code to the container image.
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the current directory to the Working Directory inside the container
COPY . .

# Copy .air.conf to the container image.
COPY .air.toml .

# Install Air
RUN go install github.com/cosmtrek/air@latest

# Expose port 5000 to the outside world
EXPOSE 5000

# Run Air
#CMD air -c .air.toml -- -h
CMD ["air", "-c", ".air.toml"]
#CMD ["air"]
