application:
  env: development

http_server:
  port: :8000
  timeout: 2

mysql:
  host:
  PORT:
  username:
  password:
  database:
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: 5

postgresql:
  host: go-backend-clean-arch_psqldb
  port: 5432
  username: admin
  password: 123456
  database: go-backend-clean-arch_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: 5

redis:
  host: go-backend-clean-arch_redis
  port: 6379
  password: 123456
  db: 0
  dial_timeout: 5
  read_timeout: 5
  write_timeout: 5
  pool_size: 10
  pool_timeout: 15
  idle_check_frequency: 500

jwt:
  secret: "MYSECRETKEY"
  refresh_secret: "MYSECRETKEY"
  access_token_expire_duration: 60
  refresh_token_expire_duration: 60
