application:
  env: development
  debug: true
  entropy_password: 80
  graceful_shutdown_timeout: "10s"

http_server:
  port: 8000
  timeout: "5s"

cors:
  allow_origins:
    - "http://example.com"
    - "https://example.com"
  allow_methods:
    - "*"
  allow_headers:
    - "*"
  allow_credentials: true

grpc_server:
  network: "tcp"
  port: 50000
  timeout: "5s"

pprof:
  port: 8001
  read_timeout: "10s"
  read_header_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

logger:
  filename: "./logs/log.json"
  max_size: 10
  max_backups: 10
  max_age: 30
  local_time: true
  compress: true

mysql:
  host: go-backend-clean-arch_mysqldb
  PORT: 3306
  username: admin
  password: password123
  database: go-backend-clean-arch_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: "5s"

postgres:
  host: go-backend-clean-arch_psqldb
  port: 5432
  username: admin
  password: password123
  database: go-backend-clean-arch_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: "5s"

redis:
  host: go-backend-clean-arch_redis
  port: 6379
  password: password123
  db: 0
  dial_timeout: "5s"
  read_timeout: "5s"
  write_timeout: "5s"
  pool_size: 10
  pool_timeout: "15s"
  idle_check_frequency: "2s"

auth:
  access_secret: "MYSECRETKEY"
  refresh_secret: "MYSECRETKEY"
  access_subject: "as"
  refresh_subject: "rs"
  access_token_expire_duration: "7h"
  refresh_token_expire_duration: "120h"
