# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'otel-collector'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'otel-collector:9090' ]

  - job_name: app
    scrape_interval: 15s
    #    metrics_path: path/metrics
    static_configs:
      #      - targets: [ 'host.docker.internal:8000' ]
      - targets: [ 'go-backend-clean-arch_app-dev:8000' ]
