CREATE TABLE permissions
(
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    allow_r    BOOLEAN   DEFAULT FALSE,
    allow_w    BOOLEAN   DEFAULT FALSE,
    allow_x    BOOLEAN   DEFAULT FALSE,
    allow_d    BOOLEAN   DEFAULT FALSE,
    deny_r     BOOLEAN   DEFAULT FALSE,
    deny_w     BOOLEAN   DEFAULT FALSE,
    deny_x     BOOLEAN   DEFAULT FALSE,
    deny_d     BOOLEAN   DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);