application:
  name: "go-backend-clean-arch"
  version: "0.1.0"
  debug: true
  env: "development"
  entropy_password: 80
  graceful_shutdown_timeout: "10s"

http_server:
  host: "localhost"
  port: 8000
  timeout: "5s"

cors:
  allow_origins:
    - "http://example.com"
    - "https://example.com"
  allow_methods:
    - "*"
  allow_headers:
    - "*"
  allow_credentials: true

grpc_server:
  network: "tcp"
  port: 50000
  max_connection_idle: "5m" # Purpose: Closes idle connections after 5 minutes of inactivity.
  timeout: "30s" # Purpose: Waits up to 20 seconds for the client to respond to a Keepalive probe before considering the connection dead.
  max_connection_age: "2h" # Purpose: Forces the connection to be refreshed after 2 hours, regardless of its state (active or idle).
  time: "1m" # Purpose: Sends a Keepalive probe every 1 minute to check the health of the connection.
  max_connection_age_grace: "60s" # Purpose: server waits 60 second for any active RPCs to finish before forcibly closing the connection

pprof:
  port: 8001
  read_timeout: "10s"
  read_header_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

logger:
  file_path: "logs"
  max_size: 10
  max_backups: 10
  max_age: 30
  local_time: true
  compress: true
  console: true
  file: false
  enable_caller: true
  enable_stack_trace: true
  level: "debug"

mysql:
  host: "go-backend-clean-arch_mysqldb"
  PORT: 3306
  username: "admin"
  password: "password123"
  database: "go-backend-clean-arch_db"
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: "5s"

postgres:
  host: "go-backend-clean-arch_psqldb"
  port: 5432
  username: "admin"
  password: "password123"
  database: "go-backend-clean-arch_db"
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: "5s"

redis:
  host: "go-backend-clean-arch_redis"
  port: 6379
  password: "password123"
  db: 0
  dial_timeout: "5s"
  read_timeout: "5s"
  write_timeout: "5s"
  pool_size: 10
  pool_timeout: "15s"
  idle_check_frequency: "2s"

auth:
  access_secret: "MYSECRETKEY"
  refresh_secret: "MYSECRETKEY"
  access_subject: "as"
  refresh_subject: "rs"
  access_token_expire_duration: "7h"
  refresh_token_expire_duration: "120h"

tracer:
  endpoint: "go-backend-clean-arch_jaeger:4318"
  app_host: "localhost" # reference http_server.host
  app_port: 8000 # reference http_server.port
  app_name: "go-backend-clean-arch" # reference application.name
  app_version: "0.1.0" # reference application.version
  app_env: "development" # reference application.env
