services:
  ####################### APPLICATION #######################
  app:
    container_name: go-backend-clean-arch_app-dev
    image: go-backend-clean-arch_app:0.1.0-dev
    build:
      context: ../..
      dockerfile: deployments/development/Dockerfile
      target: dev # For Development
    ports:
      - "8000:8000"
      - "50000:50000"
    volumes:
      - ../../:/app # important (- ./:/app)
    networks:
      - go-backend-clean-arch_network
    depends_on:
      - mysqldb
      #      - psqldb
      #      - mongodb
      - redis


      #  app-prod:
      #    build:
      #      context: ..
      #      dockerfile: ./deployments/Dockerfile
      #      target: prod # For Production

      ######################## MYSQL ########################
  mysqldb:
    container_name: go-backend-clean-arch_mysqldb
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - go-backend-clean-arch_network

    ####################### POSTGRES #######################
    #  psqldb:
    #    container_name: go-backend-clean-arch_psqldb
    #    image: postgres:latest
    #    env_file:
    #      - .env
    #    ports:
    #      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    #    volumes:
    #      - psql:/var/lib/psql/data
    #    restart: always
    #    networks:
    #      - go-backend-clean-arch_network

    ####################### MONOGO #######################
  #  mongodb:
  #    container_name: go-backend-clean-arch_mongodb
  #    image: mongo:latest
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: admin
  #      MONGO_INITDB_ROOT_PASSWORD: 123456
  #    ports:
  #      - "27017:27017"
  #    volumes:
  #      - mongodb-data:/data/db
  #    restart: unless-stopped
  #    networks:
  #      - go-backend-clean-arch_network

  ####################### PGADMIN #######################
  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: ghafbu@gmail.com
  #      PGADMIN_DEFAULT_PASSWORD: 123456
  #    volumes:
  #      - pgadmin:/var/lib/pgadmin/data
  #    ports:
  #      - "5002:80"
  #    networks:
  #      - go-backend-clean-arch_network
  #    restart: unless-stopped
  #    depends_on:
  #      - psqldb

  ####################### REDIS #######################
  redis:
    container_name: go-backend-clean-arch_redis
    image: redis:latest
    env_file:
      - .env
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    #    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - go-backend-clean-arch_network

volumes:
  mysql:
  #  psql:
  #  mongodb-data:
  #  pgadmin:
  redis:
  logs:


networks:
  go-backend-clean-arch_network:
    driver: bridge
