// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	contract "github.com/saeedjhn/go-backend-clean-arch/internal/sharedkernel/contract"
	mock "github.com/stretchr/testify/mock"

	types "github.com/saeedjhn/go-backend-clean-arch/internal/sharedkernel/types"
)

// MockOutboxInteractor is an autogenerated mock type for the OutboxInteractor type
type MockOutboxInteractor struct {
	mock.Mock
}

type MockOutboxInteractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxInteractor) EXPECT() *MockOutboxInteractor_Expecter {
	return &MockOutboxInteractor_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, events
func (_m *MockOutboxInteractor) Create(ctx context.Context, events []contract.DomainEvent) ([]types.ID, error) {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 []types.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []contract.DomainEvent) ([]types.ID, error)); ok {
		return rf(ctx, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []contract.DomainEvent) []types.ID); ok {
		r0 = rf(ctx, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []contract.DomainEvent) error); ok {
		r1 = rf(ctx, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxInteractor_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOutboxInteractor_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - events []contract.DomainEvent
func (_e *MockOutboxInteractor_Expecter) Create(ctx interface{}, events interface{}) *MockOutboxInteractor_Create_Call {
	return &MockOutboxInteractor_Create_Call{Call: _e.mock.On("Create", ctx, events)}
}

func (_c *MockOutboxInteractor_Create_Call) Run(run func(ctx context.Context, events []contract.DomainEvent)) *MockOutboxInteractor_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]contract.DomainEvent))
	})
	return _c
}

func (_c *MockOutboxInteractor_Create_Call) Return(_a0 []types.ID, _a1 error) *MockOutboxInteractor_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxInteractor_Create_Call) RunAndReturn(run func(context.Context, []contract.DomainEvent) ([]types.ID, error)) *MockOutboxInteractor_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxInteractor creates a new instance of MockOutboxInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxInteractor {
	mock := &MockOutboxInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
