// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/saeedjhn/go-backend-clean-arch/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, u
func (_m *MockRepository) Create(ctx context.Context, u entity.User) (entity.User, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u entity.User
func (_e *MockRepository_Expecter) Create(ctx interface{}, u interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, u entity.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 entity.User, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, entity.User) (entity.User, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id uint64) (entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uint64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 entity.User, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint64) (entity.User, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMobile provides a mock function with given fields: ctx, mobile
func (_m *MockRepository) GetByMobile(ctx context.Context, mobile string) (entity.User, error) {
	ret := _m.Called(ctx, mobile)

	if len(ret) == 0 {
		panic("no return value specified for GetByMobile")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, mobile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, mobile)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mobile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByMobile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMobile'
type MockRepository_GetByMobile_Call struct {
	*mock.Call
}

// GetByMobile is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
func (_e *MockRepository_Expecter) GetByMobile(ctx interface{}, mobile interface{}) *MockRepository_GetByMobile_Call {
	return &MockRepository_GetByMobile_Call{Call: _e.mock.On("GetByMobile", ctx, mobile)}
}

func (_c *MockRepository_GetByMobile_Call) Run(run func(ctx context.Context, mobile string)) *MockRepository_GetByMobile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByMobile_Call) Return(_a0 entity.User, _a1 error) *MockRepository_GetByMobile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByMobile_Call) RunAndReturn(run func(context.Context, string) (entity.User, error)) *MockRepository_GetByMobile_Call {
	_c.Call.Return(run)
	return _c
}

// IsMobileUnique provides a mock function with given fields: ctx, mobile
func (_m *MockRepository) IsMobileUnique(ctx context.Context, mobile string) (bool, error) {
	ret := _m.Called(ctx, mobile)

	if len(ret) == 0 {
		panic("no return value specified for IsMobileUnique")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, mobile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, mobile)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mobile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsMobileUnique_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMobileUnique'
type MockRepository_IsMobileUnique_Call struct {
	*mock.Call
}

// IsMobileUnique is a helper method to define mock.On call
//   - ctx context.Context
//   - mobile string
func (_e *MockRepository_Expecter) IsMobileUnique(ctx interface{}, mobile interface{}) *MockRepository_IsMobileUnique_Call {
	return &MockRepository_IsMobileUnique_Call{Call: _e.mock.On("IsMobileUnique", ctx, mobile)}
}

func (_c *MockRepository_IsMobileUnique_Call) Run(run func(ctx context.Context, mobile string)) *MockRepository_IsMobileUnique_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IsMobileUnique_Call) Return(_a0 bool, _a1 error) *MockRepository_IsMobileUnique_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsMobileUnique_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_IsMobileUnique_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
